if(WIN32)
  if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(ARCHITECTURE x64)
    set(GLEW_ARCHITECTURE ${ARCHITECTURE})
  elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(ARCHITECTURE x86)
    set(GLEW_ARCHITECTURE Win32)
  endif(CMAKE_SIZEOF_VOID_P EQUAL 8)

  if(MSVC12 OR MSVC14)
    FUNCTION(ASSIMP_COPY_BINARIES TargetDirectory)
    set(ASSIMP_MSVC_VERSION "vc${MSVC_TOOLSET_VERSION}")
    set(ASSIMP_DEBUG_BINARY assimp-${ASSIMP_MSVC_VERSION}-mtd.dll)
    set(ASSIMP_RELEASE_BINARY assimp-${ASSIMP_MSVC_VERSION}-mt.dll)
      ADD_CUSTOM_COMMAND(
        TARGET ${CMAKE_PROJECT_NAME}
        POST_BUILD 
        COMMAND ${CMAKE_COMMAND} -E copy ${ASSIMP_ROOT_DIR}/bin/${ARCHITECTURE}/$<CONFIG>/$<IF:$<CONFIG:Debug>,${ASSIMP_DEBUG_BINARY},$<IF:$<CONFIG:Release>,${ASSIMP_RELEASE_BINARY},>> ${TargetDirectory}/$<CONFIG>
        VERBATIM)
    ENDFUNCTION(ASSIMP_COPY_BINARIES)
  endif()

  FUNCTION(SDL2_COPY_BINARIES TargetDirectory)
    ADD_CUSTOM_COMMAND(
      TARGET ${CMAKE_PROJECT_NAME}
      POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy ${SDL2_ROOT_DIR}/lib/${ARCHITECTURE}/SDL2.dll ${TargetDirectory}/$<CONFIG>
      VERBATIM)
  ENDFUNCTION(SDL2_COPY_BINARIES)

  FUNCTION(GLEW_COPY_BINARIES TargetDirectory)
    ADD_CUSTOM_COMMAND(
      TARGET ${CMAKE_PROJECT_NAME}
      POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy ${GLEW_ROOT_DIR}/bin/Release/${GLEW_ARCHITECTURE}/glew32.dll ${TargetDirectory}/$<CONFIG>
      VERBATIM)
  ENDFUNCTION(GLEW_COPY_BINARIES)

endif(WIN32)
